package com.mh.cxf.day1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-13T20:03:23.074+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://day1.cxf.mh.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "http://day1.cxf.mh.com/", className = "com.mh.cxf.day1.SayHiToUser")
    @WebMethod
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "http://day1.cxf.mh.com/", className = "com.mh.cxf.day1.SayHiToUserResponse")
    public java.lang.String sayHiToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mh.cxf.day1.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://day1.cxf.mh.com/", className = "com.mh.cxf.day1.GetUsers")
    @WebMethod
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://day1.cxf.mh.com/", className = "com.mh.cxf.day1.GetUsersResponse")
    public com.mh.cxf.day1.IntegerUserMap getUsers();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://day1.cxf.mh.com/", className = "com.mh.cxf.day1.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://day1.cxf.mh.com/", className = "com.mh.cxf.day1.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );
}
